name: "CI Pipeline"

global:
  registry: "docker.io"
  image: "${global.docker.image:-python:3.9.20}"
  artifacts: "/artifacts"

stages:
  - name: setup
  - name: test
  - name: report

jobs:
  setup_environment:
    stage: setup
    commands:
      - "echo 'Setting up Python environment'"
      - "python -m pip install --upgrade pip"
      - "pip install -r requirements.txt"
      - "mkdir -p ./test-results"       # Ensure test results directory exists
      - "mkdir -p ./setup/logs"         # Ensure setup logs directory exists
    artifacts:
      destination:
        path: "./setup/logs"
      upload:
        path:
          - "./setup/*.log"

  run_tests:
    stage: test
    commands:
      - "echo 'Running pytest with verbose output...'"
      - "mkdir -p ./test-results"       # Ensure test results directory exists
      - "PYTHONPATH=. pytest test_main.py -v --tb=line --junitxml=./test-results/results.xml"
    needs: [setup_environment]
    artifacts:
      destination:
        path: "./test-results"
      upload:
        path:
          - "./test-results/results.xml"

  generate_report:
    stage: report
    commands:
      - "echo 'Generating test report'"
      - "mkdir -p ./reports"            # Ensure reports directory exists
      - "cat ./test-results/results.xml || echo 'No test results found'"
    needs: [run_tests]
    artifacts:
      destination:
        path: "./reports"
      upload:
        path:
          - "./test-results/*.xml"
          - "./reports/**/*"
    allow_failure: true