name: CI Pipeline # Added this line

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.20'
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV
      - name: Create test-results directory
        run: mkdir -p test-results
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          echo "Running pytest with verbose output..."
          pytest -v --tb=line --junitxml=test-results/results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: test-results/results.xml
          if-no-files-found: ignore