name: "CI Pipeline"

global:
  registry: "docker.io"
  image: "${global.docker.image:-python:3.9.20}"
  artifacts: "/artifacts"

stages:
  - name: setup
  - name: test
  - name: report

jobs:
  setup_environment:
    stage: setup
    commands:
      - "echo 'Setting up Python environment'"
      - "python -m pip install --upgrade pip"
      - "pip install -r requirements.txt"
      - "export PYTHONPATH=."  # Changed from GitHub Actions syntax to standard shell export
      - "mkdir -p test-results"
    artifacts:
      destination:
        path: "/setup/logs"
      upload:
        path:
          - "setup/*.log"

  run_tests:
    stage: test
    commands:
      - "echo 'Running pytest with verbose output...'"
      - "PYTHONPATH=$PWD pytest -v -p no:warnings --tb=line --junitxml=test-results/results.xml remote_repo/test_main.py"  # Added PYTHONPATH directly to the command
    needs: [setup_environment]
    artifacts:
      destination:
        path: "/test-results"
      upload:
        path:
          - "test-results/results.xml"

  generate_report:
    stage: report
    commands:
      - "echo 'Generating test report'"
      - "cat test-results/results.xml || echo 'No test results found'"
    needs: [run_tests]
    artifacts:
      destination:
        path: "/reports"
      upload:
        path:
          - "test-results/*.xml"
          - "reports/**/*"
    allow_failure: true